MusicStoreApp/MusicStoreApplication/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicStore.Domain.Domain;
using MusicStore.Service.Interface;

namespace MusicStore.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;

        public OrderController(IOrderService orderService)
        {
            this.orderService = orderService;
        }
        public IActionResult Index()
        {
            var orders = orderService.GetAllOrders();

            return View(orders);
        }

        public IActionResult Details(Guid id)
        {
            var model = new BaseEntity
            {
                Id = id
            };

            var order = orderService.GetOrderDetails(model);

            if (order == null)
            {
                return NotFound();
            }

            return View(order); 
        }


        [HttpPost]
        public IActionResult DeleteOrder(Guid id)
        {
            var order = orderService.DeleteOrder(id);
            if (order == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }
        
        
        public IActionResult DeleteAllOrders()
        {
            orderService.DeleteAllOrders();

            return RedirectToAction("Index");
        }
    }
}

MusicStoreApp/MusicStoreApplication/Controllers/UserPlaylistController.cs
using Microsoft.AspNetCore.Mvc;
using MusicStore.Domain.Domain;
using MusicStore.Domain.DTO;
using MusicStore.Service.Implementation;
using MusicStore.Service.Interface;
using System.Security.Claims;

namespace MusicStore.Web.Controllers
{
    public class UserPlaylistController : Controller
    {
        private readonly IUserPlaylistService _playlistService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IAlbumService _albumService;
        private readonly ITrackService _trackService;

        public UserPlaylistController(ITrackService trackService, IAlbumService albumService, IUserPlaylistService playlistService, IShoppingCartService shoppingCartService)
        {
            _playlistService = playlistService;
            _shoppingCartService = shoppingCartService;
            _albumService = albumService;
            _trackService = trackService;
      
        }

        public IActionResult ManagePlaylists()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var playlists = _playlistService.GetPlaylistsForUser(userId);

            var boughtItems = _shoppingCartService.GetBoughtItems(userId);

            var viewModel = new ManagePlaylistsViewModel
            {
                Playlists = playlists,
                BoughtItems = boughtItems
            };
            
           
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult CreatePlaylist(string playlistName)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _playlistService.CreatePlaylist(userId, playlistName);

            return RedirectToAction("ManagePlaylists");
        }

        [HttpPost]
        public IActionResult AddTrackToPlaylist(Guid playlistId, Guid trackId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var model = new BaseEntity
            {
                Id = playlistId
            };

            _playlistService.AddTrackToPlaylist(model, trackId, userId);
            
            return RedirectToAction("ManagePlaylists");
        }


        [HttpPost]
        public IActionResult AddAlbumToPlaylist(Guid playlistId, Guid albumId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var albumTracks = _albumService.GetTracksForAlbum(albumId);
            var model = new BaseEntity
            {
                Id = playlistId
            };
            foreach (var track in albumTracks)
            {
                _playlistService.AddTrackToPlaylist(model, track.Id, userId);
            }
            return RedirectToAction("ManagePlaylists");
        }

        [HttpPost]
        public IActionResult DeletePlaylist(Guid playlistId)
        {
            _playlistService.DeletePlaylist(playlistId);
            return RedirectToAction("ManagePlaylists");
        }


        public IActionResult PlaylistDetails(Guid playlistId)
        {
            var model = new BaseEntity
            {
                Id = playlistId
            };
            var playlist = _playlistService.GetPlaylistDetails(model);
            return View(playlist);
        }

        [HttpPost]
        public IActionResult RemoveTrackFromPlaylist(Guid playlistId, Guid trackId)
        {
            var model = new BaseEntity
            {
                Id = playlistId
            };
            _playlistService.RemoveTrackFromPlaylist(model, trackId);

            return RedirectToAction("PlaylistDetails", new { playlistId = playlistId });
        }


        [HttpPost]
        public IActionResult RemoveTrackConfirmation(Guid id)
        {
            var track = _trackService.GetTrackById(id); 
            if (track == null)
            {
                return NotFound();
            }

            return View(track); 
        }

        [HttpPost]
        public IActionResult RemoveAlbumConfirmation(Guid id)
        {
            var album = _albumService.GetAlbumById(id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }


        [HttpPost]
        public IActionResult RemoveTrack(Guid id)
        {
            var track = _trackService.GetTrackById(id);
            if (track == null)
            {
                return NotFound();
            }

            _playlistService.RemoveItemFromBoughtItems(id);
            return RedirectToAction("ManagePlaylists"); 
        }


        [HttpPost]
        public IActionResult RemoveAlbum(Guid id)
        {
            var album = _albumService.GetAlbumById(id);
            if (album == null)
            {
                return NotFound();
            }
            
            _playlistService.RemoveItemFromBoughtItems(id);
            
            return RedirectToAction("ManagePlaylists");
        }
    }
}

MusicStoreApp/MusicStoreApplication/Views/Order/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model MusicStore.Domain.Domain.Order

<h2>Order Details</h2>

<p><strong>Order ID:</strong> @Model.Id</p>
<p><strong>Order Date and Time:</strong> @Model.CreatedAt</p>
<p><strong>Owner:</strong> @Model.Owner?.UserName</p>

<h3>Bought Items:</h3>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Type</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BoughtItems)
        {
            <tr>
                <td>@item?.ProductName</td>
                <td>@item?.ProductType</td>
                <td>$@item?.Price</td>
            </tr>
        }
    </tbody>
</table>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
            <!-- Buttons side by side -->
            <a asp-action="ManagePlaylists" asp-controller="UserPlaylist" class="btn btn-outline-success mx-2">View Your Playlist</a>
            <a asp-action="Index" class="btn btn-outline-success mx-2">Check Your Orders</a>
        </div>
    </div>
</div>

MusicStoreApp/MusicStoreApplication/Views/Order/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<MusicStore.Domain.Domain.Order>

<h2>Your Orders</h2>

<table class="table">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Order Date</th>
            <th>Total Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.Id</td>
                <td>@order.CreatedAt</td>
                <td>$@order.BoughtItems.Sum(item => item.Price)</td>
                <td>
                    <div class="container">
                        <div class="row justify-content-left">
                            <div class="col-auto">
                                <form asp-action="Details" asp-route-id="@order.Id">
                                    <button type="submit" class="btn btn-success">View Order Details</button>
                                </form>
                            </div>
                            <div class="col-auto">
                                <form asp-action="DeleteOrder" asp-route-id="@order.Id">
                                    <button type="submit" class="btn btn-danger">Delete Order</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="text-center p-4 border rounded shadow-sm bg-light">
                <form asp-action="DeleteAllOrders">
                    <button type="submit" class="btn btn-danger">Delete All Orders</button>
                </form>
            </div>
        </div>
    </div>
</div>