MusicStoreApp/MusicStoreApplication/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Mvc;
using MusicStore.Domain.Domain;
using MusicStore.Service.Interface;

namespace MusicStore.Web.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IArtistService _artistService;

        public ArtistController(IArtistService artistService)
        {
            _artistService = artistService ?? throw new ArgumentNullException(nameof(artistService));
        }
        // Get Artists
        public IActionResult Index()
        {
            var artists = _artistService.GetAllArtists();
            return View(artists);
        }

        // Get  /Artist/Details/{id}
        public IActionResult Details(Guid id) 
        {
            var artist = _artistService.GetArtistById(id);
            return View(artist);
        }

        // Get /Artist/Create
        [HttpGet]
        public IActionResult Create ()
        {
            return View();
        }

        // Post /Artist/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create (Artist artist)
        {
            if (ModelState.IsValid)
            {
                _artistService.CreateArtist(artist);
                return RedirectToAction("Index");
            }
            return View(artist);
        }

        // Get /Artist/Edit/{id}
        [HttpGet]
        public IActionResult Edit (Guid id) 
        {
            var artist = _artistService.GetArtistById(id);
            return View(artist);
        }
        // Post /Artist/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Artist artist)
        {
            if (ModelState.IsValid)
            {
                _artistService.UpdateArtist(artist);
                return RedirectToAction("Index");
            }
            return View(artist);
        }
        // POST /Artist/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _artistService.DeleteArtist(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MusicStoreApp/MusicStoreApplication/Controllers/BookStoreController.cs
using Microsoft.AspNetCore.Mvc;
using MusicStore.Service.Interface;

namespace MusicStore.Web.Controllers
{
    [Route("bookstore")]
    public class BookStoreController : Controller
    {
        private readonly IBookService _service;

        public BookStoreController(IBookService service)
        {
            _service = service;
        }


        public ActionResult HomePage() 
        {
            return View();
        }

        // View for displaying all books
        [Route("books")]
        public IActionResult Index()
        {
            var books = _service.GetBooks();
            return View(books);
        }

        // View for displaying all bookstores
        [Route("bookstores")]
        public IActionResult BookStores()
        {
            var stores = _service.GetBookStores();
            return View(stores);
        }

        // View for displaying books in stores (combined information)
        [Route("booksinstores")]
        public IActionResult BooksInStores()
        {
            var booksInStores = _service.GetBooksInStores();
            return View(booksInStores);
        }
    }
}

MusicStoreApp/MusicStoreApplication/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicStore.Domain.Domain;
using MusicStore.Service.Interface;

namespace MusicStore.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;

        public OrderController(IOrderService orderService)
        {
            this.orderService = orderService;
        }
        public IActionResult Index()
        {
            var orders = orderService.GetAllOrders();

            return View(orders);
        }

        public IActionResult Details(Guid id)
        {
            var model = new BaseEntity
            {
                Id = id
            };

            var order = orderService.GetOrderDetails(model);

            if (order == null)
            {
                return NotFound();
            }

            return View(order); 
        }


        [HttpPost]
        public IActionResult DeleteOrder(Guid id)
        {
            var order = orderService.DeleteOrder(id);
            if (order == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }
        
        
        public IActionResult DeleteAllOrders()
        {
            orderService.DeleteAllOrders();

            return RedirectToAction("Index");
        }
    }
}

MusicStoreApp/MusicStoreApplication/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using MusicStore.Domain.Domain;
using MusicStore.Domain.DTO;
using MusicStore.Service.Interface;
using System.Security.Claims;

namespace MusicStore.Web.Controllers
{
    public class ShoppingCartController : Controller
    {

        private readonly IShoppingCartService _shoppingCartService;
        private readonly IAlbumService _albumService;
        private readonly ITrackService _trackService;
        private readonly IOrderService _orderService;

        public ShoppingCartController(IOrderService orderService, IShoppingCartService shoppingCartService, IAlbumService albumService, ITrackService trackService)
        {
            _shoppingCartService = shoppingCartService;
            _albumService = albumService;
            _trackService = trackService;
            _orderService = orderService;
        }

        public IActionResult ViewCart()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? null;
            var cartItems = _shoppingCartService.GetCartItems(userId);
            var totalPrice = cartItems.Sum(item => item.Price);
            var boughtItems = new List<BoughtItem>();
            foreach (var cartItem in cartItems)
            {
                BoughtItem boughtItem = new BoughtItem
                {
                    Id = Guid.NewGuid(),
                    Price = cartItem.Price,
                    ProductId = cartItem.ProductId,
                    ProductName = cartItem.ProductName,
                    ProductType = cartItem.ProductType,
                };

                boughtItems.Add(boughtItem);

            }
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cartItems,
                TotalPrice = totalPrice,
                BoughtItems = boughtItems,
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult RemoveFromCart(Guid id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? null;

            if (userId != null)
            {
                _shoppingCartService.RemoveItemFromCart(id, userId);
            }
            
            return RedirectToAction("ViewCart");
        }


        public IActionResult ClearCart()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? null;
            
            var shoppingCart = _shoppingCartService.GetCartForUser(userId);

            _shoppingCartService.ClearCart(userId);

            return RedirectToAction("ViewCart");
        }

        [HttpPost]
        public IActionResult Checkout(List<BoughtItem> BoughtItems)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? null;
            var order = _orderService.CreateOrder(userId, BoughtItems);
            _shoppingCartService.BuyTracks(userId, BoughtItems);
            
            _shoppingCartService.ClearCart(userId);
            /*return RedirectToAction("ManagePlaylists", "UserPlaylist");*/
            return RedirectToAction("Details", "Order", new { id = order.Id });
        }

    }
}

MusicStoreApp/MusicStoreApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicStoreApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicStoreApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicStoreApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artists</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Track" asp-action="Index">Tracks</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Index">Albums</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="ViewCart">Shopping Cart</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserPlaylist" asp-action="ManagePlaylists">Playlists</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookStore" asp-action="HomePage">BookStore - Partner Team</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MusicStoreApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>